locale = "en-US"
label  = "English"
weight = 1
title  = "Yehonatan Kazarski | Cyber Research"

[params]
  displayName = "EN"
  isoCode     = "en"
  dateFormat  = "2 January 2006"
  description = "Deep dives into anything cyber related."
  copyright   = "© { year } Yehonatan Kazarski"

[params.author]
  name     = "Yehonatan Kazarski"
  image    = "img/author.jpg"
  headline = "Cybersecurity Enthusiast"
  bio      = "Hey, I'm Yehonatan — but everyone calls me **Yoni** :) A cybersecurity enthusiast and a computer admirer in general. I document my research, CTF writeups, and projects here."
  links = [
    { github   = "https://github.com/Tasty-Murder" },
    { linkedin = "https://www.linkedin.com/in/yehonatan-kazarski-b22434165" },
    { twitter  = "https://twitter.com/YKazarski" }
  ]
