[[main]]
  name    = "Research"
  pageRef = "research"
  weight  = 10

[[main]]
  name    = "Projects"
  pageRef = "projects"
  weight  = 20

[[main]]
  name    = "About"
  pageRef = "about"
  weight  = 30

[[main]]
  name    = "RSS"
  pre     = "rss"
  url     = "/feed.xml"
  weight  = 40
